# etcd 配置文件
# 基本配置
name: etcd0
data-dir: /etcd-data

# 监听地址
listen-client-urls: http://0.0.0.0:2379
listen-peer-urls: http://0.0.0.0:2380

# 广播地址
advertise-client-urls: http://etcd:2379
initial-advertise-peer-urls: http://etcd:2380

# 集群配置
initial-cluster: etcd0=http://etcd:2380
initial-cluster-token: etcd-cluster
initial-cluster-state: new

# 日志配置
log-level: info